name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      
      - name: Rename PDF file
        run: mv cv.pdf aaron_murniadi_cv_v${{ github.run_number }}.pdf
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: aaron_murniadi_cv_v${{ github.run_number }}.pdf
          path: aaron_murniadi_cv_v${{ github.run_number }}.pdf
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Automated build v0.1-${{ github.run_number }}
          draft: false
          prerelease: false
      
      - name: Set upload_url as an environment variable
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }} 
          asset_path: aaron_murniadi_cv_v${{ github.run_number }}.pdf
          asset_name: aaron_murniadi_cv_v${{ github.run_number }}.pdf
          asset_content_type: application/pdf
